trigger:
  - master
variables:
  - group: DEV

stages:
  - stage: Build
    displayName: Build Package
    jobs: 
    - job: BuildPackage
      pool: LAPTOP-Q338O4FK
      steps:    
      - task: UiPathPack@2
        inputs:
          versionType: 'CurrentVersion'
          projectJsonPath: '$(Build.SourcesDirectory)\project.json'
          outputType: 'Process'
          orchestratorConnection: 'UiPath DEV'
          outputPath: '$(Build.ArtifactStagingDirectory)'
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: drop

  - stage: Assest
    displayName: Create Assests
    jobs:
      - job: CreateAssests
        pool: LAPTOP-Q338O4FK
        steps:
        - task: UiPathAssets@2
          inputs:
            orchestratorConnection: 'UiPath DEV'
            folderName: 'Shared'
            assetActionType: 'Deploy'
            csvFile: '$(Build.SourcesDirectory)\Data\Assests.csv'

  - stage: DeployDEV
    displayName: Deploy build artifact to DEV
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: deployDEV
        displayName: Deploy package to DEV Orchestrator
        pool: LAPTOP-Q338O4FK
        environment: DEV
        strategy:
         runOnce:
          deploy:
           steps:
            - task: UiPathDeploy@2
              inputs:
                orchestratorConnection: 'UiPath DEV'
                packagesPath: '$(Pipeline.Workspace)\drop\'
                folderName: 'Shared'
  - stage: TestDEV
    displayName:  Test After Publish
    dependsOn: DeployDEV
    condition: succeeded()
    jobs:
      - job: TestDEV
        pool: LAPTOP-Q338O4FK
        steps:
          - task: UiPathTest@2
            inputs:
              testTarget: 'TestSet'
              orchestratorConnection: 'UiPath DEV'
              testSet: 'UiPathAzureDevOps_Tests'
              folderName: 'Shared'
              testReportDestination: '$(Pipeline.Workspace)\drop\'

